debian-unstable=https://cloud.debian.org/images/cloud/sid/daily/latest/debian-sid-genericcloud-amd64-daily.qcow2
debian-12=https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
debian-13=https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
ubuntu-18.04=https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
ubuntu-20.04=https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
ubuntu-22.04=https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
ubuntu-24.04=https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
ubuntu-25.04=https://cloud-images.ubuntu.com/minimal/releases/plucky/release/ubuntu-25.04-minimal-cloudimg-amd64.img
ubuntu-25.10=https://cloud-images.ubuntu.com/minimal/releases/questing/release/ubuntu-25.10-minimal-cloudimg-amd64.img
ubuntu-26.04=https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img
